.defaults:
  disallowed: &defaultDisallowed
    - status
    - kind
    - apiVersion
  properties: &defaultProperties
    enabled: metachart.interface.boolean
    metadata: metachart.api.meta.v1.ObjectMeta
  rootKey: &defaultRootKey
    disallowed: *defaultDisallowed
    properties: *defaultProperties

definitions:
  - https://raw.githubusercontent.com/iponweb/schemas/main/json-schemas/kubernetes/v1.33.2-strict/_definitions.json
  - https://raw.githubusercontent.com/iponweb/schemas/main/json-schemas/external-secrets/v0.18.2-strict/_definitions.json

rules:
  #: Common
  #:
  #:  meta.v1.ObjectMeta
  - target: metachart.api.meta.v1.ObjectMeta
    source: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    allowed:
      - annotations
      - labels
      - finalizers
      - namespace
      - name

  #: external-secrets.io/v1
  - target: metachart.api.io.external-secrets.apis.externalsecrets.v1.ClusterExternalSecret
    source: io.external-secrets.apis.externalsecrets.v1.ClusterExternalSecret
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.externalsecrets.v1.ClusterSecretStore
    source: io.external-secrets.apis.externalsecrets.v1.ClusterSecretStore
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.externalsecrets.v1.ExternalSecret
    source: io.external-secrets.apis.externalsecrets.v1.ExternalSecret
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.externalsecrets.v1.SecretStore
    source: io.external-secrets.apis.externalsecrets.v1.SecretStore
    <<: *defaultRootKey

  #: external-secrets.io/v1alpha1
  - target: metachart.api.io.external-secrets.apis.externalsecrets.v1alpha1.PushSecret
    source: io.external-secrets.apis.externalsecrets.v1alpha1.PushSecret
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.externalsecrets.v1alpha1.ClusterPushSecret
    source: io.external-secrets.apis.externalsecrets.v1alpha1.ClusterPushSecret
    <<: *defaultRootKey

  #: generators.external-secrets.io/v1alpha1
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.ACRAccessToken
    source: io.external-secrets.apis.generators.v1alpha1.ACRAccessToken
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.ClusterGenerator
    source: io.external-secrets.apis.generators.v1alpha1.ClusterGenerator
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.ECRAuthorizationToken
    source: io.external-secrets.apis.generators.v1alpha1.ECRAuthorizationToken
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.Fake
    source: io.external-secrets.apis.generators.v1alpha1.Fake
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.GCRAccessToken
    source: io.external-secrets.apis.generators.v1alpha1.GCRAccessToken
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.GithubAccessToken
    source: io.external-secrets.apis.generators.v1alpha1.GithubAccessToken
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.Grafana
    source: io.external-secrets.apis.generators.v1alpha1.Grafana
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.MFA
    source: io.external-secrets.apis.generators.v1alpha1.MFA
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.Password
    source: io.external-secrets.apis.generators.v1alpha1.Password
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.QuayAccessToken
    source: io.external-secrets.apis.generators.v1alpha1.QuayAccessToken
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.STSSessionToken
    source: io.external-secrets.apis.generators.v1alpha1.STSSessionToken
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.UUID
    source: io.external-secrets.apis.generators.v1alpha1.UUID
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.VaultDynamicSecret
    source: io.external-secrets.apis.generators.v1alpha1.VaultDynamicSecret
    <<: *defaultRootKey
  - target: metachart.api.io.external-secrets.apis.generators.v1alpha1.Webhook
    source: io.external-secrets.apis.generators.v1alpha1.Webhook
    <<: *defaultRootKey
